== El Progreso Cristiano de George Whitehead

Al recordar al Señor, nuestro clemente Dios,
y Sus misericordiosos tratos conmigo desde mi juventud--cómo me encontró entre Sus ovejas
perdidas y extraviadas en las estériles montañas de las profesiones religiosas infructuosas;
cómo me atrajo a una experiencia interior de Su poder
y de Su obra santificadora en mi corazón,
y al conocimiento de Su enseñanza y ministerio espiritual;
cómo me permitió ministrar gradualmente a otros a partir de mi propia experiencia,
así como también sufrir pacientemente por Él, en rendición de vida y libertad,
siendo ayudado por Su poder a través de muchas y grandes pruebas y profundos sufrimientos,
y a través de muchas notables liberaciones y preservaciones,
incluso desde mis años de juventud--me siento impulsado
a dejar algunos comentarios o pasos a otros,
mediante un relato histórico de mi progreso en la obra y servicio del
Señor. Para este propósito he compilado varios de mis documentos,
notas y memorias de las experiencias y ejercicios pasados,
deseando fervientemente que la publicación de estas cosas conduzca
a la gloria de Dios y al honor de Su excelente nombre,
y sea de provecho para el lector serio en la consideración de Su bondad y gracia divinas,
que perduran para siempre para todos los que verdaderamente Lo aman y temen.

Desde las primeras inclinaciones y deseos que el Señor se
complació misericordiosamente suscitar en mi corazón,
hacia Su bendita verdad como está en Cristo Jesús,
fui persuadido a buscar el conocimiento de Dios,
a aprender cómo llegar a estar verdaderamente arrepentido,
y a experimentar una verdadera corrección de mi vana conducta de vida, a la que yo,
desde mi infancia, había sido propenso.
Al ser parcialmente educado bajo el ministerio Presbiteriano, me fue dado ver,
a una edad temprana,
varias maneras en las que este pueblo quedaba corto de todo
lo que ellos profesaban y proclamaban en sus predicaciones,
oraciones y adoración,
de tal manera que (aún antes de haber escuchado del pueblo llamado Cuáqueros),
no podía unirme activamente con los presbiterianos.
Por ese tiempo estaba confundido en cuanto a lo que
mi espíritu secretamente deseaba y necesitaba,
y vivía desconcertado y deambulando,
buscando la verdad entre otros grupos y persuasiones
que tenían algunas nociones más altas y más refinadas,
con respecto a los dones espirituales, etc.
En ese entonces tenía unos catorce años.

Poco tiempo después oí de un pueblo llamado Cuáqueros,
que temblaba ante la Palabra de Dios,
y al observar cómo era injuriado y criticado por personas libertinas y malvadas,
hizo que yo investigara más sobre ellos.
Como resultado, el Señor me dio creer que estos eran, en efecto, Su pueblo,
y contendí por ellos y sus principios hasta donde me habían sido presentados favorablemente,
incluso antes de que yo hubiera estado en alguna de sus reuniones,
o hubiera oído a alguno de sus ministros.

Y aunque el Señor había levantado buenos deseos en mí hacia Él,
para que yo experimentara el verdadero arrepentimiento para vida,
esos deseos eran a menudo apagados y mi mente alejaba,
por una disposición frívola y superficial, pues tenía gran afición por la música,
diversión y otras vanidades, como muchos otros niños y jóvenes.
Sin embargo, le agradó al Señor por su gran misericordia,
seguirme en secreto con juicio y reprensión en mis años más jóvenes,
y a menudo renovaba los deseos en mí en pos del camino correcto.
Pero como me mantuve oyendo a los sacerdotes y a otros profesantes del cristianismo,
no tenía un verdadero reposo para mi mente,
pues entonces no conocía ni seguía esa luz de Cristo en mí,
que me convencía y reprendía por los pecados de mi juventud.
En aquellos primeros días la luz brillaba en las tinieblas, como en un lugar oscuro,
y a menudo era nublada antes de que comenzara a vencer las tinieblas.
Porque así como el Espíritu del Señor una vez se movió sobre las aguas,
cuando las tinieblas estaban sobre la faz del gran abismo,
antes de que Su obra de antaño fuera forjada, así también,
a fin de llevar a cabo Su obra en la nueva creación
para hacernos nuevas criaturas en Cristo Jesús,
se mueve Su Espíritu sobre los corazones de las personas,
incluso cuando son inestables como agua,
y Su luz resplandece en ellas antes de que conozcan al Dios vivo,
para darles el conocimiento de la gloria y poder de Dios, y de Su amado Hijo Jesucristo.

Durante una conversación religiosa con unos pocos jóvenes con inclinación sobria,
oí de unas personas llamadas Cuáqueros en Sedbergh, en Yorkshire, y en Kendal Barony,
en Westmoreland, y después de mucho buscar y deambular,
quería asistir a una de sus reuniones,
la cual se iba a realizar en la casa de un tal capitán Ward,
en un lugar llamado Sunny Bank, cerca de la capilla de Grayrig.
Entré a la reunión y me senté entre ellos sobriamente,
y después de un corto tiempo en silencio,
un Amigo llamado Thomas Arey habló un rato de la liberación de Israel de Egipto,
del Faraón y de sus capataces, haciendo referencia a la liberación,
viaje y progreso espiritual del pueblo del Señor en Su camino y obra.
Pensé que yo había entendido todo eso fácilmente, en un sentido alegórico o espiritual,
pero me parecía que una gran obra del poder del Señor estaba ocurriendo en la reunión,
quebrantando los corazones de muchos con gran dolor, lloro y contrición de espíritu,
y creí que era una '`tristeza según Dios`' por el pecado,
para el sincero arrepentimiento.

Esta opinión fue confirmada en mí,
al ver a una joven doncella salir corriendo de la reunión llorando.
Yo la seguí con una actitud seria para observar su dolorosa condición,
y la vi sentada en el suelo con su cara hacia la tierra,
como si no le importara la presencia de alguien más, lamentándose amargamente y clamando:
"`¡Señor, límpiame! ¡Oh, Señor, límpiame!`"
Esto afectó tierna y profundamente mi corazón mucho más que lo que había oído ese día;
de hecho,
me alcanzó más que todas las predicaciones que alguna
vez había escuchado de cualquier hombre u hombres.
Para mí esto fue un auténtico testimonio (al testificar
el Espíritu del Señor en mi espíritu),
de que esta era una verdadera obra del poder de Dios sobre el corazón de ella,
el cual también vi operando en los corazones de los otros, haciendo que temblaran,
se entristecieran y se humillaran,
para llevarlos al verdadero arrepentimiento y enmienda de vida,
y a una experiencia de la obra de regeneración y de santificación del pecado y la inmundicia.
En realidad, resultó ser así para muchos; ¡gloria sea dada a nuestro Dios para siempre!

Tras una seria reflexión, estas cosas causaron una profunda impresión en mi mente,
y se afirmó más en mí la creencia a la que había llegado antes,
de que el Señor estaba obrando en medio de este pueblo pequeño y despreciado,
y que Él estaba a punto de reunir y levantar un pueblo para Él,
que Lo adorara en Espíritu y en verdad,
y no en las formas muertas y vacías que son establecidas en la voluntad del hombre.
Tales adoradores (nos dice Cristo) son los que el Padre busca que lo adoren.

Bajo estas consideraciones, pronto fui persuadido a dejar a los párrocos,
quienes eran ministros hechos por la voluntad del hombre,
sin autoridad divina impartida por Dios, ni comisionados por Cristo a enseñar a otros.
Pues al ver, que por su orgullo y codicia no eran buenos ejemplos para el rebaño,
sino que vivían en contra del mandato de Cristo y del ejemplo de Sus ministros,
supe que debía alejarme de ellos, y lo hice en un corto tiempo,
conforme el Señor (mediante Su luz) abría mis ojos para ver la ceguera de aquellos guías,
a quienes yo había seguido por educación y tradición.

Y aunque me topé con oposición y palabras duras de algunos parientes
cercanos y de otras personas que escuchaban a esos sacerdotes,
seguí confesando y defendiendo la verdad según la pequeña medida
de entendimiento que tenía. Y al ser débil y no más que un joven,
y acosado con varias tentaciones y desalientos,
el Señor mi Dios me ayudó y me persuadió a tomar una decisión,
no solo a dejar completamente a los mencionados sacerdotes,
sino también a asistir constantemente a las reuniones
de Su despreciado pueblo llamado Cuáqueros,
y sentarme entre ellos, aunque no fueran más que unos pocos en número,
en comparación con lo que han llegado a ser desde entonces.
Las reuniones que yo frecuentaba,
por un tiempo se realizaron en la parroquia de Sedbergh, en Yorkshire,
en la casa de Thomas Blaykling,
cuya familia era honesta y de buena reputación. También en la casa de Richard Robinson,
en Brigflats, que era un hombre inocente y fiel.
Y algunas veces en Grayrig y alrededores, cerca de Kendal en Westmoreland,
el condado donde nací.

En un corto tiempo fui plenamente convencido de la verdad de los principios de los Cuáqueros.
Mi mente estaba vuelta hacia la luz,
y yo estaba persuadido y resuelto a perseverar entre los Amigos,
aún antes de haber oído alguna vez a nuestro querido Amigo George Fox.
La primera vez que lo oí ministrar fue en una reunión vespertina en Sunny Bank,
en la casa del capitán Henry Ward.
En ese tiempo yo me mantenía muy bajo, serio y atento en mi mente,
dispuesto a ver y a probar por mí mismo, para mi propia satisfacción interna.
En realidad, vi y sentí que su testimonio era de peso y profundo,
que procedía de la vida y la experiencia, que demostraba revelación divina,
que tenía la intención de llevar a un sentimiento
y sentido internos de la vida y poder de Cristo,
y a la operación santificadora de dicha vida y poder en el corazón.
Su predicación no fue con presumida elocuencia u oratoria,
ni con sabiduría humana, sino en la sencillez del evangelio,
y con el fin de volver la mente a la luz y vida de Cristo.
El Señor, en verdad bendijo abundantemente su ministerio hacia muchos.

Encontré gran satisfacción,
estando ya unido al pueblo que en escarnio era llamado Cuáqueros,
y por la gracia de Dios, habiendo resuelto continuar,
perseverar en su comunión y esperar en Dios y Su luz (con la que
Él había alumbrado mi entendimiento en una buena medida).
Pues tras haber "`recibido el amor de la verdad,`"^
footnote:[2 Tesalonicenses 2:10]
fuimos conscientes de que nuestra sociedad y conversación unos con otros eran útiles,
consoladoras y llevaban a nuestra edificación y consuelo.
Yo amaba y me deleitaba grandemente en la libre conversación
y comunión con Amigos sobrios y fieles.
Cuando era un niño de escuela, en la escuela gratuita en Blencoe, Cumberland,
me encantaba retirarme con algunos de los estudiantes sobrios
y serios (aunque eran humildes y pobres en el mundo),
en lugar de la compañía de niños vanos y extravagantes que eran
muy dados a jugar y a la diversión. En compañía de los primeros,
había mucho provecho para nuestro aprendizaje,
pues nos compartíamos los resultados de nuestros estudios entre nosotros.
Y esto es mucho más cierto en el sentido espiritual y superior,
cuando llegamos a conocer en algún grado la bendita
Verdad en la luz de nuestro Señor Jesucristo.
Nuestra sociedad cristiana y la comunicación de nuestras experiencias internas,
redundaron en nuestra mutua ayuda y edificación en
el amor de la verdad como está en Cristo;
pues Él es la luz y la vida, y nuestro gran Apóstol y ministro,
que enseña a Sus verdaderos seguidores a beneficiarse
de ese amor y de esa vida que fluyen de Él. De hecho,
Él es la Fuente y Fundamento de todas nuestras misericordias,
ayudas y alientos vivos en Su camino y obra--¡a Quien únicamente
sean dadas la alabanza y la gloria para siempre!

Después de que decidí y establecí en mi mente y consciencia,
unirme en comunión con el ya mencionado pueblo y frecuentar sus asambleas,
llegué a experimentar (mediante la asistencia divina) algunos progresos
en la obra del Señor Jesucristo en mí. Pues el Señor,
por la luz y gracia de Su Santo Espíritu,
me persuadió plenamente de que sin ser convertido, así como también, convencido,
y de que sin ser regenerado, santificado y verdaderamente haber nacido de nuevo,
no podía entrar o ser heredero de Su reino.
Me fue dado ver que la tristeza según Dios que produce arrepentimiento,
y una verdadera enmienda de vida,
debían ser forjadas por Su gracia y buen Espíritu en mí,
y que '`sin santidad nadie verá al Señor.`'^
footnote:[Hebreos 12:14]

Ante estas y otras serias reflexiones cristianas, fui persuadido por la gracia de Dios,
a rendirme en obediencia para seguir a Jesucristo,
para creer y obedecer la luz que Él me había dado,
y diligentemente esperar en ella para recibir el
poder de Él y llegar a ser un verdadero hijo de Dios;
porque a todos los que verdaderamente reciben a Cristo el Hijo de Dios,
Él les da potestad de ser hechos hijos de Dios.^
footnote:[Juan 1:12]

Vi que mi lugar era retirarme internamente hacia la luz, hacia la gracia de Dios,
hacia la Semilla inmortal e incorruptible, o Palabra implantada,
la cual es el don divino y el principio^
footnote:[Al momento de escribir esto,
la palabra _principio_ se usaba comúnmente para referirse
a "`la fuente u origen de cualquier cosa;
aquello de lo que procede una cosa; la sustancia primordial;
la causa operativa`"--[.book-title]#Webster`'s Dictionary 1828 Edition.#]
vivo, frecuentemente testificado entre la Sociedad de Amigos,
en concordancia con las Sagradas Escrituras.
Y en la medida que mi mente se volvía hacia esta luz,
en esa medida veía claramente mi verdadero estado interno y externo,
cuán caído estaba en un estado degenerado, y cuán depravado,
corrompido y alienado estaba de la vida de Cristo y de Dios.
La vanidad misma de la mente,
y los pensamientos en los que yo había estado vagando
y alejándome de la luz y vida de Cristo,
se convirtieron en una indecible carga y prueba.
De hecho, yo anhelaba ser liberado,
para poder ser verdaderamente renovado en el espíritu de mi mente,
y en este unirme al Señor.

Así fui persuadido a esperar en la luz "`en el camino de tus juicios,`"^
footnote:[Isaías 26:8]
y a soportar y someterme a Sus paternales castigos, y a Sus reprensiones que instruyen,
creyendo que "`Sion será rescatada con juicio, y los convertidos de ella con justicia.`"^
footnote:[Isaías 1:27]
Los vanos pensamientos, imaginaciones y vagabundeos de la mente,
se convirtieron en una fuente de sufrimiento y carga para mí,
y yo buscaba fervientemente al Señor y Su poder para que los suprimiera,
y me diera victoria sobre todos ellos,
y para mantener mi mente en el Señor y poder disfrutar paz interior en Él.

Yo tenía una guerra espiritual que atravesar,
un cuerpo de pecado del que debía ser despojado y que debía ser destruido.
Y aunque yo era joven y no había madurado--como otros de más años que
son culpables de grandes males por su larga permanencia y costumbre en
el pecado--encontré una verdadera necesidad de la obra de santificación,
de limpieza interior del pecado, y de un verdadero nuevo nacimiento.
Este es ese nacimiento y vida que vienen de arriba,
lo único que tiene derecho al reino de Cristo y de Dios,
y que ninguna persona inmunda puede heredar.

Al esperar en Dios, y sinceramente buscarlo con mi mente internamente retirada,
y mi alma deseando y respirando en pos de Su nombre y poder, Él muchas veces se agradó,
misericordiosamente, en renovar Sus compasivas visitas a mi pobre alma,
y en medio del juicio y los castigos, recordar misericordia, para que Lo reverenciara.^
footnote:[Salmo 130:4]
La consciencia de esto con frecuencia quebrantaba y enternecía mi corazón,
y me hacía estar aún más atento a la obra del Señor nuestro Dios,
y a considerar más menudo la operación de Su mano divina,
cuyos tratos conmigo eran en juicio y castigo.

Su Palabra eterna, por medio de Sus juicios,
me llevaba a temer y a temblar en Su presencia,
y Su misericordia me causaba quebrantamiento y verdadera ternura de corazón,
lo cual experimenté a menudo.
En el recuerdo vivo de estas cosas,
todavía encuentro un gran motivo para atribuirle alabanza y gloria a Su excelente nombre,
poder y divina bondad, manifestados a través de Su amado Hijo--es decir,
el Hijo de Su amor, nuestro bendito Señor y Salvador Jesucristo.

Muchos de los sacerdotes Presbiterianos en Westmoreland,
y otras partes del norte de Inglaterra,
parecían muy envidiosos de nosotros en los años 1652, 1653 y 1654.
Y en sus conferencias y sermones injuriaban y reprochaban a los Cuáqueros y sus ministros,
llamándolos engañadores y anticristos que habían venido en los últimos tiempos.
Ellos recogían cualquier reporte malvado y falso que podían,
para encolerizar a sus crédulos oyentes contra nosotros,
y poner vecinos y familias en desacuerdo y sembrar discordia.

Algunos de sus oyentes, incluso de mi propios parientes,
cuando regresaban de su adoración pública y de oír un sermón contra los Cuáqueros,
se llenaban y enfurecían con falsas, y a menudo, absurdas acusaciones y calumnias.
Yo a veces les daba una respuesta cristiana, que cuando la rechazaban,
con frecuencia encontraba que mi lugar era estar
en silencio y dejarlos vociferar y burlarse.
Los líderes y sacerdotes hacían que el pueblo errara, y con su agria levadura,
agriaban los espíritus de muchos con enemistad,
por lo que muchos eran heridos y prejuiciados contra la verdad.

Mis padres fueron lastimados por ellos, y por un tiempo los incitaron contra mí,
hasta que el Señor volvió sus corazones y abrió sus entendimientos,
para que vieran mucho mejor de lo que podían ver al seguir guías ciegos,
cuya obra era crear divisiones.
Mis padres y parientes, me tenían un gran afecto natural y cuidaban de mí a su manera.
E incluso cuando parecían más opuestos y ofendidos,
porque yo había dejado su iglesia y sus ministros,
y me había unido al pueblo llamado Cuáqueros (lo cual fue una gran prueba para mí),
su angustia y pesar provenían más de la influencia de sus sacerdotes,
y del temor que tenían de mi infortunio o pérdida de posición en el mundo,
que por algún prejuicio contra mí o mi profesión religiosa.
Ellos conservaron un verdadero amor y afecto natural hacia mí,
mientras estuve ausente por casi tres años,
por el ministerio y servicio de la Verdad (en cuyo tiempo sufrí varios y duros encarcelamientos).
Y después, cuando regresé a visitarlos, se reconciliaron y me amaron,
y sus entendimientos y corazones se abrieron hacia mí y mis amigos
que llegaban a visitarme cuando estaba en la casa de ellos.

Mi madre, algunos años antes de su muerte,
estaba realmente convencida de la Verdad y se convirtió
en una Amiga en su corazón. Mi padre,
al ver la corrupción, orgullo y avaricia de los sacerdotes,
conservó un amor hacia los Amigos hasta el final de sus días. Igualmente mi hermana Ana,
antes de la muerte de su madre, se hizo amiga de la Verdad y de los Amigos,
y continuó siendo una mujer honesta, amable y servicial hasta su muerte.

Entonces,
cuando los sacerdotes o ministros de las parroquias
vieron que no podían detener el progreso,
ni la propagación de la bendita Verdad, ni el poder de Cristo,
ni evitar el crecimiento de nuestros amigos en él, por medio de todos sus discursos,
sermones y predicaciones injuriosos contra nosotros,
se esforzaron por encolerizar a los magistrados,
jueces y gobierno contra el pueblo llamado Cuáqueros.
Debido a esto, muchos jueces y oficiales fueron instigados a perseguir,
y a encerrar a muchos de nuestros Amigos en las cárceles de Kendal y Appleby en Westmoreland,
por dar testimonio contra ellos.
Antes de viajar a la parte sur de Inglaterra, fui movido, en el pavor y temor del Señor,
a dar testimonio público contra la maldad de los sacerdotes,
en varios de sus lugares de adoración en Westmoreland.
Sin embargo,
le plació al Señor en ese momento preservarme de cualquier daño o encarcelamiento,
al tener una obra adicional para en mí en otras partes de la nación.

Las reuniones a las que yo pertenecía en Westmoreland y Yorkshire,
entre los años 1652 y 1654, se realizaron regularmente,
y a menudo eran en silencio o con la declaración de unas pocas palabras,
mientras éramos internamente ejercitados en esperar en el
Señor. Después de haber estado por algún tiempo entre ellos,
el Señor a veces se complacía, mediante Su poder y Palabra de vida,
en enternecer y abrir mi corazón y mi entendimiento,
y de vez en cuando me daba (y a algunos otros también)
unas pocas palabras vivas para compartir,
para el consuelo de ellos y mío;
pues Él abrió nuestros corazones con gran amor los unos por los otros,
el cual luego se incrementó y creció entre nosotros.
¡Bendito sea el Señor nuestro Dios para siempre!
Fue a partir de estas y otras reuniones frecuentemente en silencio,
que el Señor se agradó en levantar y poner de manifiesto a testigos vivos,
fieles ministros y verdaderos profetas,
en los primeros días en Westmoreland y otras partes del norte de Inglaterra,
en los años 1654 y 1655.

Verdaderamente se puede decir, que en estos últimos días y tiempos,
el Señor nuestro Dios se ha complacido en visitar
esta isla con el día y poder de Su evangelio,
en concordancia con Su promesa a los gentiles, y a "`las costas +++[+++que]
esperarán su ley,`" para que Su elegido, Su Cristo, en quien Su alma se deleita,
traiga juicio a los gentiles.
(Isaías 42) Porque nosotros los que esperábamos en verdadero silencio en Él,
y poníamos nuestra mirada en Su aparición interna
en el Espíritu y en la obra de Su poder en nosotros,
llegamos a ver y a sentir verdaderamente renovada nuestra fuerza en la fe viva,
en el verdadero amor y en el celo santo por Su nombre y poder; de manera tal,
que el Señor gradualmente nos llevó a experimentar lo que
dijo en la antigüedad por medio de Su santo profeta:
"`Guarden silencio ante Mí, costas, y renueven sus fuerzas los pueblos.
Acérquense y entonces hablen, juntos vengamos a juicio.`"^
footnote:[Isaías 41:1 (NBLA)]

Este guardar silencio ante el Señor,
y acercarse a Él en un verdadero estado silencioso de espíritu,
para primero oír lo que el Señor nos habla,
antes de hablarles a otros (sea en juicio o misericordia),
fue la forma que se nos mostró para renovar nuestra fuerza,
y para convertirnos en Sus ministros--hablándoles
a otros solo lo que Él nos había hablado primero.
¡Ojalá el pueblo tomara en cuenta esto, verdadera y seriamente!
Entonces no correrían en pos, ni seguirían, a los ministros,
sacerdotes o profetas que corren cuando Dios no los ha enviado, diciendo:
"`Así dice el Señor,`" cuando Dios no les ha hablado.
Estos son aquellos de los que el Señor ha declarado:
Ellos "`hacen errar a mi pueblo con sus mentiras y con sus lisonjas,
y yo no los envié ni les mandé; y ningún provecho hicieron a este pueblo.`"^
footnote:[Jeremías 23:32]

Incluso antes de que yo fuera considerado un Cuáquero,
o me hubiera unido en comunión con ellos,
ya había recibido algo de entendimiento con respecto a esos ministros párrocos,
o sacerdotes, de que ellos no habían sido enviados por Dios ni por Cristo,
y que no tenían una comisión divina, ni un llamado al ministerio.
Vi que ellos habían sido formados y establecidos por la voluntad del hombre,
y que no predicaban su experiencia, sino lo que habían estudiado o reunido de otros,
o compuesto de antemano, sin haber esperado,
ni recibido revelaciones ni instrucciones directas del Espíritu de Cristo.
De hecho, muchos ni siquiera creían en la influencia del Espíritu,
ni en la necesidad de ayuda directa del Espíritu y poder de Jesucristo
para ministrar o predicar de Él en estos días. Por el contrario,
ellos han negado abiertamente estas cosas,
y se han opuesto a nuestro testimonio cristiano de las mismas,
lo que ninguna de las verdaderas ovejas o rebaño de Cristo haría,
porque ellas oyen y conocen la voz de Cristo y lo siguen--al
ser Él su líder y comandante--pero no seguirán a un extraño.

Su orgullo y codicia pusieron contra ellos a muchas personas bien dispuestas,
e hicieron que algunas los dejaran, más aún,
cuando muchos de ellos mostraron su envidia y codicia al perseguir,
encarcelar y oprimir enormemente al pueblo llamado Cuáqueros,
por concienzudamente rehusarse a pagar diezmos, o no satisfacer su avaricia.
Pues, por el escaso valor de un diezmo de cerdo o ganso,
han sentenciado sin piedad a muchos hombres honestos a prisión,
como si valoraran el cerdo o el ganso del prójimo (que codiciaban)
más que la libertad o vida de su prójimo.
Pero cuando los sacerdotes se convirtieron en perseguidores y opresores inflexibles,
esto en gran medida se volvió su propia desventaja, desgracia y vergüenza,
porque puso contra ellos a personas de tierno corazón,
e hizo que nuestro número aumentara.
Aunque débiles en nosotros mismos,
nuestras opiniones con respecto a esos ministros o párrocos
acosadores llegaron a consolidarse más en nosotros,
sabiendo que la religión cristiana no es una religión cruel o acosadora, sino tierna,
amorosa y compasiva.
También sabíamos, que los verdaderos cristianos eran perseguidos, pero no perseguidores;
que eran víctimas pacientes, pero no victimarios; que oraban por sus enemigos,
pero no buscaban venganza contra ellos.

Yo fui convencido y persuadido desde temprano de que los diezmos
no debían ser requeridos ni pagados bajo la dispensación del evangelio.
Y las razones principales por la que el pueblo llamado Cuáqueros,
por el bien de la consciencia,
no puede pagar diezmos ni oblaciones en el día del evangelio son: Primero,
porque el ministerio de Cristo es y debe ser un ministerio de gracia;
tal como Él les ordenó a Sus ministros: "`De gracia recibisteis, dad de gracia.`"^
footnote:[Mateo 10:8 (o "`gratuitamente habéis recibido, gratuitamente dad.`"
RV1602 Purificada)]
Segundo, porque Jesucristo, la única ofrenda,
el gran Apóstol y Sumo Sacerdote de nuestra profesión cristiana,
por medio de la ofrenda y sacrificio de Sí mismo, le ha puesto fin a los diezmos,
a las oblaciones e ingresos de los sacerdotes,
junto con todo el sacerdocio y el primer pacto,
bajo los cuales estas cosas eran celebradas y mantenidas.
Esto queda claro por medio de las razones y argumentos que da el apóstol,
e insta en su carta a los Hebreos, en los capítulos 7, 8, 9 y 10. De modo que,
demandar diezmos y oblaciones, ingresos o cuotas sacerdotales,
parece ser una negación del Cristo crucificado,
y de Su ofrecimiento de una vez por todas, y consecuentemente,
una negación de los privilegios de la dispensación y ministerio del nuevo pacto,
que fueron ratificados por Él a través de la muerte en la cruz.

Ahora vuelvo a mi propio estado interior,
y a la experiencia de mi viaje y progreso espiritual.
El Señor misericordiosamente se agradó en conducirme a través de la ley,
y a través del juicio y la condenación contra el
pecado en la carne (que Cristo vino a condenar),
a fin de llevarme a la más gloriosa ministración,
y a la "`ley del espíritu de vida en Cristo Jesús,`"^
footnote:[Romanos 8:2]
lo cual es el fundamento de los apóstoles y profetas.
Fui llevado a experimentar el misterio del ministerio de arrepentimiento de Juan,
el lavamiento de la regeneración, el hacha puesta a la raíz del árbol, así como también,
la poda de todas las ramas superfluas,
para que fuera forjada una obra completa de regeneración. Estas
cosas fueron espiritual y gradualmente experimentas internamente,
a través de la obediencia a la fe, y esperar y perseverar en la gracia,
luz y verdad recibidas de Cristo, a fin de obtener victoria sobre el pecado y Satanás,
y para que su obra de pecado, y el cuerpo de pecado,
fueran destruidos de raíz a rama.

Vi que yo debía mantenerme atento a Su obra interna de gracia,
de santificación y de santidad, para que esta pudiera continuar y prosperar,
cualesquiera que fueran las revelaciones, profecías,
visiones o descubrimientos divinos que a Él le placiera darme en cualquier momento,
por medio de Su Santo Espíritu,
para mi aliento o para el incremento de la fe y de la esperanza.
Aunque muchas debilidades y tentaciones me acompañaban, Su gracia era suficiente para mí,
y a menudo me daba fuerza y victoria sobre el enemigo de mi alma,
y frustraba sus malvados designios.
Cuando quería entrar como un diluvio, con multitud de tentaciones y estratagemas,
el Espíritu del Señor levantaba un estandarte contra él
y lo repelía. ¡Gloria sea dada a nuestro Dios y al Cordero,
en quien está nuestra salvación y fortaleza por los siglos de los siglos,
cuyo reino es un reino eterno, y Su dominio sin fin!

Nuestro bendito Señor Jesucristo declaró: "`El que quiera hacer la voluntad de Dios,
conocerá si la doctrina es de Dios.`"^
footnote:[Juan 7:17]
Y así, en el día de Su poder, conforme aparecía la luz,
una disposición para hacer Su voluntad era forjada en mi corazón,
según me era dada a conocer, y me disponía a seguirlo a Él,
negándome a mí mismo y tomando la cruz cada día,
lo cual todo hombre debe hacer si busca ser Su discípulo.
De esta manera, por medio de Su luz y enseñanza, llegué vívidamente a creer,
a entender y a recibir esas doctrinas y principios
que son esenciales para la vida y salvación cristiana,
especial y particularmente los siguientes:

[.numbered-group]
====

[.numbered]
1+++.+++ El amor gratuito de Dios en Su amado Hijo Jesucristo,
y Su gracia universal ofrecida a toda la humanidad en Él;
que Cristo murió por todos los hombres que estaban muertos en sus pecados,
y se dio a Sí mismo en rescate por todos, para testimonio, a su debido tiempo,
del amor gratuito de Dios hacia la humanidad en general.
Porque fue por la gracia de Dios que Cristo probó la muerte por cada hombre,
para que ahora,
la gracia y el amor gratuitos de Dios hacia la humanidad sean testificados y evidentes,
tanto en la muerte de Cristo por todos los hombres, como al ser la "`luz del mundo,`"^
footnote:[Juan 8:12]
"`que alumbra a todo hombre que viene a este mundo.`"^
footnote:[Juan 1:9 (SRV-BRG)]

[.numbered]
2+++.+++ La necesidad de que el hombre se arrepienta verdaderamente,
crea el evangelio y se convierta a Cristo, de manera tal,
que realmente Lo reciba y experimente una fe viva y firme en Él, en Su luz,
nombre y poder, para llegar a ser hijo de Dios.
Porque es por medio de Su poder, y a través de la fe en este,
que los hombres son hechos hijos de Dios,
y no mediante una profesión externa o creencia tradicional,
sin recibir espiritualmente a Cristo en sus corazones.
Pues los hombres deben conocer Su obra de fe y poder dentro de ellos,
para la conversión y cambio real de sus corazones y mentes,
por medio del lavamiento de la regeneración, el cual es santificación,
o del único bautismo salvador del Espíritu que nos lava de nuestros pecados,
y nos restaura a novedad de vida en Cristo Jesús.

[.numbered]
3+++.+++ Entender y experimentar la verdadera y aceptable adoración a Dios,
que es "`en Espíritu y en verdad,`" y no según las
tradiciones o formas humanas prescritas por los hombres.
Es en verdad una gran satisfacción para el alma,
estar retirada en mente y espíritu hacia el Espíritu Santo y verdad, es decir,
hacia la Palabra viva, en la que Dios puede ser efectivamente adorado,
reverenciado y esperado en verdadera humildad; pues aquí,
Él consuela y refresca a Su pueblo, y hace que se levante alabanza viva.

====

Todas estas cosas concuerdan con el testimonio de las Sagradas Escrituras,
y son experimentadas y entendidas por cada verdadero creyente en Cristo,
quien es nuestra luz y nuestra vida.

Desde mi infancia, había amado la Biblia y había amado leerla,
pero realmente no entendí ni experimenté las doctrinas esenciales de la salvación,
ni la dispensación del nuevo pacto, hasta que mi mente se volvió a la luz de Cristo,
la Palabra viva y eterna, a "`la exposición de +++[+++la cual]
imparte luz; da entendimiento a los sencillos.`"^
footnote:[Salmo 119:130 (NBLA)]
Sin embargo,
confieso que fue de cierta ventaja para mí haber leído con frecuencia las Sagradas Escrituras,
incluso cuando era ignorante y no entendía la grandeza
y excelencia de las cosas testificadas en ellas.
Porque cuando el Señor abrió, en cierta medida, mis ojos a Su bendita verdad,
mi frecuente lectura de las Escrituras desde niño, y mi familiaridad con ellas,
demostró ser de ayuda y ventaja en mis meditaciones secretas,
cuando un sentido y consuelo vivos con respecto a las cosas contenidas en ellas,
me eran en algún grado dados por el Espíritu.
Como resultado de eso,
fui aún más inclinado a leer y a considerar con seriedad los escritos sagrados.
En realidad, descubrí que todas las promesas de Dios, que son sí y amén en Cristo Jesús,
son verdaderamente consoladoras cuando son aplicadas por el mismo Espíritu,
pues Él no hará una aplicación equivocada de ellas.
El Espíritu nunca les aplicará la paz a los impíos,
ni a las personas que viven en sus pecados; ni les dirá a los injustos,
que son justos o rectos ante los ojos de Dios.

Se dice que a través de "`la fe que está en Cristo Jesús,`" las Sagradas Escrituras
hacen al hombre de Dios "`sabio para salvación,`" al ser provechosas para él,
porque son útiles "`para enseñar, para redargüir, para corregir,
para instruir en justicia, a fin de que el hombre de Dios sea perfecto,
enteramente preparado para toda buena obra.`"^
footnote:[2 Timoteo 3:15-16]
No hay duda de que Pablo estimaba que el conocimiento que tenía Timoteo de las
Sagradas Escrituras "`desde la niñez,`" era de alguna ventaja y ayuda para él,
pero el beneficio de ellas es principalmente a través de "`la fe que es en Cristo Jesús.`"

Al ser debidamente consideradas estas cosas,
deseo que los padres cristianos no sean negligentes
al hacer que sus hijos lean las Sagradas Escrituras,
sino que los impulsen a aprender y a leer frecuentemente la Biblia.
Esto puede ser una verdadera ventaja, y provechoso para ellos,
cuando lleguen a tener sus entendimientos alumbrados y a
conocer la Verdad como está en Cristo Jesús. De hecho,
he observado que cuando los niños leen la Biblia,
a veces se ven muy afectados por las cosas buenas que han leído. Y estos,
a partir de una creencia e impresión secretas estampadas en sus jóvenes corazones,
han estado más inclinados a leer seriamente las Escrituras,
cuando el Señor posteriormente abra sus entendimientos
por medio de la luz de Su gracia dentro de ellos.

Pero, por lo que he declarado aquí,
en elogio a las Sagradas Escrituras y a la ventaja de ellas,
no quiero que se entienda que limito el don del Espíritu de Dios,
o Su ministerio y divina gracia, en los iletrados, no educados,
o personas de poca educación, tales como aradores, vaqueros, pastores, pescadores, etc.
Porque Dios ciertamente ha dado Su buen Espíritu y Sus dones espirituales a estos,
y ha prometido derramar Su '`Espíritu sobre toda carne,
para que los hijos y las hijas profeticen.`'^
footnote:[Joel 2:28; Hechos 2:17]
Y Moisés dijo: "`Ojalá todo el pueblo de Jehová fuese profeta,
y que Jehová pusiera su espíritu sobre ellos`"^
footnote:[Números 11:29]--entre los cuales están incluidos, tanto hombres como mujeres,
como aprendidos y no aprendidos.

Mi entrada en el Espíritu, mi comienzo en Él,
y mi creer en la luz de nuestro Señor Jesucristo,
fue para realmente entrar en el nuevo pacto y en la dispensación del evangelio,
porque Cristo fue '`puesto por luz y por pacto,`' y para
ser la salvación de Dios hasta los confines de la tierra.^
footnote:[Isaías 42:6; 49:8]
Este nuevo pacto es un pacto de gracia, de misericordia y de paz con Dios,
en Su amado Hijo Jesucristo.
Es la reconciliación, o acuerdo cercano con Dios y Cristo,
al que el hombre debe entrar si alguna vez quiere disfrutar verdadera paz.
Este pacto es donde todo el pueblo del Señor y los verdaderos cristianos, Lo conocen,
desde el menor hasta el mayor, y en el que todos son enseñados por Dios,
al tener Sus leyes escritas en sus corazones por Su dedo divino,
y puestas en sus mentes por Su Espíritu Santo.

En este pacto el Señor borra de Su pueblo,
todas las transgresiones anteriores y abandonadas,
y no recuerda sus pecados e iniquidades en tanto
continúen en este pacto eterno y en Su bondad.
Él es un Dios que mantiene el pacto y la misericordia para siempre,
con todos los que verdaderamente le temen.
Y por tanto, mi clamor, la respiración de mi alma, mi esfuerzo interno y espiritual,
mi vigilancia y oración, han sido para este fin: "`¡Oh, Señor,
presérvame y guárdame en Tu santo temor, en humildad, y en la consciencia de Tu poder,
para que yo nunca me aparte de Ti, ni de Tu pacto, ni deshonre tampoco Tu Verdad,
ni nuestra santa profesión!`" Hasta ahora el Señor me ha
ayudado en mi viaje y carrera espiritual hacia el premio.
Le atribuyo la gloria y alabanza solo a Él, porque "`Él da esfuerzo al cansado,
y multiplica las fuerzas al que no tiene ningunas,`" y muchas veces,
en mi estado de debilidad, Él ha manifestado Su fuerza.

Mi primera creencia y persuasión cuando fui convencido de la Verdad fue,
que todos los que son verdaderamente llamados a ser ministros
del eterno evangelio y predicadores de la justicia,
deben ser santificados, divinamente inspirados y dados para esa obra y servicio sagrados.
Deben ser cuidadosos para que su conducta sea tal que adorne el evangelio;
deben vivir buenas vidas, así como también hablar buenas palabras;
deben ser hombres que temen a Dios y rehúyen el mal,
que odian la codicia y no ofenden en nada, para que el ministerio no sea censurado.
Con respecto a esto,
el Señor ha puesto sobre mí un cuidado piadoso (que
todavía permanece sobre mí hasta este día,
tanto para mí mismo como para otros),
para que nuestro ministerio sea verdaderamente irreprensible
y ninguna ofensa le sea atribuida.
¿De qué le sirve a alguien tener el nombre de que vive, cuando está muerto?
¿De qué le valdrá? O, ¿de qué les sirve a las personas ligeras, vanas, orgullosas,
codiciosas o sin santificación, afirmar que están en el camino santo,
cuando ellas mismas son totalmente impías, están contaminadas y son pecadoras?
En mis años más jóvenes fui plenamente persuadido,
de que Jesucristo no emplearía personas malvadas
o corruptas en Su sagrado servicio del ministerio,
ni concedería Su presencia a personas como estas en su predicación,
sin importar qué pretendan o profesen en Su nombre.
Cristo acompañará a los ministros fieles,
que verdaderamente Lo obedecen y siguen Su ejemplo,
con Su presencia y ayuda divinas en sus ministerios y testimonios del evangelio.
Sí, a estos Él les dio el gran aliento y promesa:
"`He aquí yo estoy con vosotros todos los días, hasta el fin del mundo.`"

Lo que el noble profeta David oraba fervientemente en el Salmo cincuenta y uno,
realmente describe el estado y la condición de los verdaderos ministros del evangelio,
cuyo ministerio es asistido con el poder y la presencia de Dios, y de este modo,
hecho eficaz para la conversión de los pecadores a Él. "`Lávame más y más de mi maldad,
y límpiame de mi pecado.
Crea en mí, oh Dios, un corazón limpio,
y renueva un espíritu recto dentro de mí. No me eches de delante de ti,
y no quites de mí tu santo Espíritu.
Vuélveme el gozo de tu salvación, y espíritu noble me sustente.
_Entonces_ enseñaré a los transgresores tus caminos, y los pecadores se convertirán a ti.`"

A estas cosas he aspirado sinceramente,
y he deseado anhelosamente del Señor. Internamente en espíritu
he trabajado por ellas con todo mi corazón y con toda mi alma.
Y puedo realmente decir que el Señor, en cierta medida,
me respondió antes de que yo comenzara a viajar en el extranjero
en el ministerio del evangelio de Cristo--es decir,
el evangelio de Su gracia, cuya gracia Él gradualmente me dio a mí e incrementó en mí,
a partir de comienzos muy pequeños. ¡Bendito sea Su muy excelente nombre para siempre;
porque Él le prometió a Su pueblo: "`Y os daré pastores según mi corazón,
que os apacienten con ciencia y con inteligencia.`"^
footnote:[Jeremías 3:15]

Los únicos verdaderos pastores y ministros son los dados por Dios.
Él ha dado muchos, y aún dará más a Su iglesia en el día del evangelio,
según lo testificado por el que predicaba tanto la venida
de Cristo en la carne como el misterio de Su venida en Espíritu:
"`El misterio que había estado oculto desde los siglos y edades,
pero que ahora ha sido manifestado a sus santos,
a quienes Dios quiso dar a conocer las riquezas de
la gloria de este misterio entre los gentiles;
que es Cristo en vosotros, la esperanza de gloria, a quien anunciamos,
amonestando a todo hombre, y enseñando a todo hombre en toda sabiduría,
a fin de presentar perfecto en Cristo Jesús a todo hombre; para lo cual también trabajo,
luchando según la potencia de él, la cual actúa poderosamente en mí.`"^
footnote:[Colosenses 1:26-29]
Y en concordancia con una verdadera creencia y persuasión
de que Dios revelaría este misterio de Cristo en nosotros,
con ternura de corazón, me dedicaba a esperarlo para poder experimentar,
presenciar y sentir el poder y la venida de Cristo internamente en el Espíritu,
tanto para santificar mi corazón, como para darme entendimiento para hacer Su voluntad.

Cuando Él me llamó a dar testimonio de Su nombre y poder,
y de Su obra interior y espiritual en el hombre,
me dispuse en espíritu a esperar que Su poder y Su Espíritu se movieran y obraran en mí,
para poder trabajar en Su servicio según Su obra en mí,
y no correr o luchar en mi propia voluntad, sabiduría o fuerza,
sabiendo que sin Cristo (Su poder y presencia, ayuda y consuelo),
no podía hacer nada por mí mismo, ni por nadie más. Cuando mi habilidad era pequeña,
y muchas veces me encontraba en gran debilidad, temor y temblor, el Señor me ayudaba,
y aumentaba mi fuerza y mi habilidad en mis labores, más allá de lo esperado.
Pero aún desde mi primeros viajes,
siempre reposó sobre mí el cuidado de solo ministrar de acuerdo
a la habilidad y don que mi Padre celestial me había dado,
y así mantenerme dentro del rango de mi propio don y habilidad.
Por tanto, cuando el Espíritu del Señor se revelaba y se movía en unas pocas palabras,
yo no me atrevía a excederlo, y cuando había acabado me sentaba en silencio.
Muchas veces, esperando en el Señor, y secretamente respirando hacia Él en silencio,
surgía el manantial de vida y revelaba un consejo fresco,
para el refrescamiento y consolación de mi propia alma y las de otros.
Mi alma a menudo ha sido llevada muy bajo,
y el Señor me ha ayudado y ha renovado mi fuerza para perseverar en Su servicio.
Así me di cuenta de que cuánto más bajo estoy, y cuánto más temo al Señor,
aunque débil y sencillo, más manifiesta Él Su poder a través mío,
y bendice mis esfuerzos y servicio.
¡Qué Aquel que es digno para siempre, reciba la alabanza de todos!

Después de muchos benditos y consoladores temporadas y tiempos
de refrigerio provenientes de la presencia de nuestro Padre celestial,
los cuales disfrutamos en nuestras reuniones en la parte norte;
y después de haber descargado mi consciencia en el testimonio de la Verdad,
tanto en palabra como en conducta cristiana hacia mis padres y familiares,
una pesada preocupación vino sobre mí (después de la cosecha, en el año 1654),
de dejar la casa de mi padre y el condado de Westmoreland, y viajar al sur.
Yo di a conocer mi expectativa a algunos Amigos,
y mi querido amigo Edward Edwards--que entonces era
joven y vivía en la casa de Gervase Benson,
cerca de Coatley Cragg,
que aún no había sido llamado al ministerio--se ofreció a viajar conmigo y hacerme compañía.
Ambos decidimos viajar a pie y caminamos juntos unas sesenta millas hasta York,
donde nos quedamos dos o tres días y asistimos a la reunión de Amigos el Primer-día,
en la cual, aunque pequeña,
el Señor me dio unas pocas palabras para vívidamente declarar entre ellos.

De ahí viajamos hacia el sur en Yorkshire,
y nos encontramos con nuestro amado amigo y hermano en Cristo, George Fox,
en la casa del capitán Bradford, donde asistimos a una reunión con él por la noche.
Después viajamos a East Holderness, a la casa de Joseph Storr,
donde nos encontramos otra vez con George Fox y varios otros Amigos,
y fuimos consolados juntos.
Viajamos un poco más por esa región,
y asistimos a algunas otras reuniones con George Fox,
quien entonces tenía el servicio público puesto completamente sobre él,
para el fortalecimiento y establecimiento de los Amigos en la Luz y en la Verdad.
Antes de dejar ese condado,
tenía sobre mí unos testimonios para dar en dos '`casas
del campanario,`' pero no me topé con ningún trato duro,
excepto haber sido arrastrado fuera del lugar de reunión. Pero el Señor me sostuvo
en fe y esperanza para el servicio que Él tenía para mí más al sur.

Mi honesto y querido amigo Edward Edwards y yo nos separamos en Holderness,
y entonces Thomas Ralison (quien había viajado con George Fox) se fue conmigo a Hull,
desde donde cruzamos el río Humber en un bote, a unas cuatro millas de Lincolnshire.
En el bote tuvimos una compañía grosera, abusiva y borracha,
quienes nos amenazaron y nos insultaron,
pero el Señor nos guardó de ser dañados por ellos.
Al día siguiente, que era el Primer-día,
vino sobre mí la carga de ir y dar testimonio de la Verdad en dos
'`casas del campanario,`' uno en la mañana y el otro en la tarde.
No sufrí daño ni violencia, excepto ser jalado o empujado fuera de la reunión,
pero Thomas Ralison, que estaba en la reunión de la tarde, fue maltratado y golpeado,
y luego seguido al campo por un montón de tipos.
Yo estaba dolido de que fuera tan malvadamente tratado.

Al día siguiente él y yo nos separamos, y yo viajé hacia Lincoln,
asistiendo a una reunión en el camino,
en la que el Señor abrió mi boca con un testimonio vivo.
Me quedé en Lincoln una noche,
estando presionado en mi espíritu a viajar hacia Cambridge y Norwich,
aunque tenía que viajar solo y todavía a pie.
Fui a Cambridge desde Lincoln en menos de tres días,
a pesar de que mi pies estaban bastante ásperos y ampollados,
aún antes de salir de Yorkshire.
Sin embargo, se curaron mientras viajaba, incluso antes de llegar a Norwich,
y fui preservado en buena salud todo el tiempo,
lo cual agradecidamente estimo como una gran misericordia de Dios,
siendo que entonces no tenía dieciocho años.

En Cambridge fui recibido amablemente por el concejal Blakeling y su esposa,
y por los pocos Amigos de ahí. James Parnell se reunió conmigo antes de que yo me fuera,
y nos consolamos juntos.
Después de dos o tres días de estancia, yo seguía presionado en mi espíritu por Norwich.
De Cambridge, Thomas Lightfoot viajó conmigo hacia Norwich,
y llegamos a unas tres millas de Thetford, en Norfolk, la primera noche,
con el clima húmedo y lluvioso.
Resultó difícil conseguir alojamiento por nuestro dinero en la pequeña villa donde estábamos,
pues la gente era muy huraña y tímida con nosotros.
Sin embargo, encontramos un casa donde vendían cerveza,
y los convencimos de que nos acomodaran por una noche,
pero la habitación en la que nos alojamos era fría y decrépita,
y la ventana estaba tan destrozada que la nieve caía sobre nosotros.
Al día siguiente viajamos a Windham, que está a casi seis millas de Norwich,
donde Robert Constable y su esposa nos recibieron amablemente;
ambos habían sido convencidos de la Verdad un poco antes,
por el testimonio de nuestro querido amigo Richard Hubberthorn,
que entonces estaba prisionero en el castillo de Norwich,
por dar testimonio público de la Verdad en la '`casa del campanario`' de Windham.

Al siguiente día nos fuimos de Windham a Norwich,
y visité a Richard Hubberthorn en prisión,
donde alegremente nos abrazamos en cariñoso y tierno amor,
y nos consolamos juntos en el Señor. En ese entonces había unos pocos Amigos
en esa ciudad que habían sido convencidos por su testimonio y sufrimientos,
y algunos que habían ido a visitarlo a la prisión
se habían unido a la Verdad y a los Amigos.

El Amigo más conocido y servicial en esta ciudad era Thomas Symonds, un maestro tejedor,
que recibía Amigos viajeros en su hogar.
Él era un hombre amoroso y honesto,
y recibió un don en el ministerio y fue fiel hasta la muerte.
Vivió y murió en la fe,
y fue hecho partícipe de las promesas que son sí
y amén en Cristo Jesús. Él era ejemplar en la Verdad,
y servicial tanto en la ciudad de Norwich como en el condado de Norfolk, donde vivía.

Aunque yo esperaba sufrir encarcelamiento en esa ciudad,
el Señor ordenó que yo tuviera libertad por algunas semanas,
para tener varias reuniones en la casa de Thomas Symonds, en Norwich,
y en la casa de Robert Harvey, en Windham,
que era un guantero y un hombre honesto e inocente,
que había recibido la Verdad en el amor de ella.
A una de las reuniones en la casa de R. Harvey, llegó un capitán, un tal John Lawrence,
quien luego de ser tiernamente afectado por la Verdad,
quería que yo tuviera una reunión en la casa de él en Wramplingham,
a lo cual yo estaba muy dispuesto, y muy contento de hacer.

A esa reunión llegaron tres sacerdotes con la intención de oponerse a mí,
Jonathan Clapham, sacerdote del pueblo, y otros dos.
Ellos se quedaron en el salón hasta que la reunión estuvo lista,
y luego se asomaron para verme.
Mi apariencia fue despreciable a sus ojos,
pues me consideraron un muchachito debido a mi juventud,
e incompetente para conversar con ellos.
Sin embargo, Jonathan Clapham,
al fin empezó a oponerse y a interrogarme acerca de nuestra '`falta
de respeto`' por no inclinarnos y arrastrar nuestro pie,^
footnote:[Los saludos normales entre compañeros en ese tiempo involucraban
arrastrar por el suelo y hacia atrás el pie derecho,
e inclinarse mientras se quitaban el sombrero,
y luego se adulaban unos a otros con títulos como "`su Señoría,`" "`su Eminencia,`" etc.]
etc., pues era un hombre ambicioso,
que estimaba más el honor mundano y el respeto de las personas,
que buscar el honor que es de arriba.
Él abogaba por estas tradiciones tanto como podía, y yo les declaraba a él y a su grupo,
en el espíritu de mansedumbre, las respuestas que el Señor me daba,
adecuadas y de las Escrituras, y además,
exponía algunas de sus prácticas no bíblicas e injustificables.
Al experimentar el poder y el consejo del Señor sobre mí,
me fue dado dominio para defender la Verdad, para confusión de sus oponentes.
Después de un corto tiempo, Jonathan Clapham y otro sacerdote se retiraron,
pero el tercero se quedó hasta que terminó la reunión;
pues después de que terminó la contienda con los otros dos sacerdotes,
tuve una muy buena y bendita oportunidad de declarar la Verdad.
Aclaré varios asuntos importantes,
según le plació al Señor revelármelos y ensanchar mi espíritu para demostrarlos,
de modo que, en una reunión, la mayoría de la familia de John Lawrence, junto con otros,
fueron convencidos y persuadidos del camino de la Verdad.

El Señor me dio gran consuelo y ánimo ese día,
por medio de Su asistencia divina en Su obra y servicio.
Los Amigos presentes estaban enormemente satisfechos,
y el desprecio de los sacerdotes hacia mí (un pobre siervo y débil instrumento),
se volvió desprecio y desgracia para ellos mismos,
de modo que tuve (y a menudo he tenido desde entonces) verdadero
motivo de atribuirle la gloria y alabanza al Señor nuestro Dios,
y de declarar: "`De la boca de los niños y de los que maman, fundaste la fortaleza,
a causa de tus enemigos, para hacer callar al enemigo y al vengativo.`"^
footnote:[Salmo 8:2]

John Lawrence recibió la Verdad y libremente se rindió en obediencia a ella.
Cuando experimentó el comienzo en el Espíritu, no se devolvió, sino que perseveró,
y dio fiel testimonio al sufrir por la verdad,
tanto en persona como en la pérdida de bienes.
La conversión de él y de su familia a la Verdad, y su unión a los Amigos,
fueron un medio para alejar a muchas personas de los sacerdotes mercenarios y acercarlos
a Cristo--a Su luz y ministerio de gracia--para que pudieran conocerlo como su Ministro,
su Sumo Sacerdote, su Pastor y Obispo de sus almas.

Por ese tiempo, en los meses noveno y décimo de 1654,
tuve varias reuniones en y cerca de Wymondham, y en Norwich.
El Señor estaba conmigo y me ayudó a declarar Su nombre y verdad,
a predicar el evangelio eterno, a volver a muchos de las tinieblas a la luz,
y del poder del pecado y Satanás a Dios y Su poder,
para que las personas no continuaran en las formas y sombras vacías,
sino que llegaran a la vida y sustancia de la verdadera religión, al poder de la piedad,
y a conocer a Cristo como su maestro y líder,
cuya voz oyen Sus ovejas y no siguen la voz de un extraño. Muchos
fueron convencidos de la verdad de estas cosas en aquellas partes,
y se volvieron a la luz de Cristo dentro de ellos.
Que la obra del Señor Lo alabe,
la cual comenzó en aquellos días y ha prosperado desde entonces en aquellos lugares,
tanto en la descendencia de muchos que recibieron el amor de la verdad,
como en muchos otros,
a quienes el Señor ha bendecido en su obediencia y disposición a servirle,
tras haber llegado al amanecer del día del poder de Cristo,
en el que Su pueblo se ofrece voluntariamente.

La primera oposición que encontré en una reunión, sucedió en la casa de Thomas Symonds,
en la ciudad de Norwich, y fue con un predicador Antinomiano,^
footnote:[El _Antinomianismo_ (que significa "`contra la ley`") es
la creencia de que la gracia en el nuevo pacto libera a los hombres
de cualquier obligación de guardar la ley moral de Dios.]
que por la lucha de Pablo en Romanos 7,
alegaba que el pecado debía continuar durante toda la vida,
incluso en los mejores de los santos, y que aunque los hombres continuaran pecadores,
no estaban bajo la ley sino bajo la gracia, y que eran estimados justos en Cristo.
Nos topamos con una doctrina complaciente del pecado muy similar
a esta en los profesantes cristianos de aquellos días,
a quienes resistimos en el nombre del Señor, como hice con este Antinomiano,
y prevalecí sobre él y sus argumentos perversos, por medio de la ayuda del Señor,
para su gran confusión. Vi que los Antinomianos eran muy oscuros y corruptos en doctrina,
y que estaban en contra de la obra de Cristo, que consiste en destruir el pecado,
y salvar a Su pueblo del pecado y la transgresión.

En esa reunión también había algunas personas de las llamadas Ranters^
footnote:[Los _Ranters_ eran un grupo no conformista que surgió a mediados de los 1600,
y que recibieron su nombre debido a sus extravagantes discursos y prácticas.
Algunos de ellos parecen haber sido genuinos buscadores de la verdad,
quienes (en palabras de William Penn),
"`no se mantuvieron en la humildad ni en el temor de Dios,
y después de abundante revelación, se exaltaron,
y por falta de mantener sus mentes en humilde dependencia de Aquel que había
abierto sus entendimientos para que vieran las grandes cosas de Su ley,
corrieron en sus propias imaginaciones y las mezclaron con las revelaciones divinas,
dando a luz un monstruoso nacimiento para escándalo de aquellos que temían a Dios.`"
Los _Ranters_ a menudo interrumpían las reuniones religiosas
establecidas vociferando a gritos,
cantando, tocando instrumentos o haciendo toda clase de ruidos fuertes.],
que permiten libertades corruptas y carnales.
Uno de los jefes parecía aceptar lo que yo estaba diciendo contra el Antinomiano,
pero me fue dado el discernimiento de que él era de un espíritu corrupto,
y le dije que yo también rechazaba su espíritu,
pues sentía un celo por parte del Señor contra ambos.
El poder del Señor estaba sobre todo y me alentaba en Su servicio de una reunión a otra,
a tal punto,
que yo estaba seguro de que el Señor estaba conmigo
y que fortalecía mi espíritu en Su obra y servicio.
Cuanto más viajaba y trabajaba en ella,
más se incrementaba mi fuerza en Él--por lo que mi alma
a menudo alababa Su glorioso nombre y le cantaba alabanzas,
incluso en lugares solitarios.

Poco tiempo después de esto, tuve otra reunión en la casa de Thomas Symonds en Norwich,
un Primer-día de la semana.
A esa reunión llegó un grupo de personas que estaban en el espíritu de ranterismo,
y también la misma persona que parecía que estaba de mi lado contra el opositor Antinomiano.
El poder y el pavor del Señor Dios cayeron pesadamente sobre mí,
al dar testimonio contra el pecado y la iniquidad,
tanto contra la raíz como la rama--contra los deseos de la carne, los deseos de los ojos,
la vanagloria de la vida y el amor al mundo.
La poderosa Palabra del Señor atravesó la reunión,
y derribó tan maravillosamente los espíritus de aquellos Ranters,
y otros espíritus libertinos, que después se acercaron a mí como hombres muy heridos,
derrotados en sus conceptos altivos y fluctuantes, y cuestionándose su salvación,
la que antes habían considerado como una montaña que no podía ser movida.
Sí, ahora tenían dudas y temores, y estaban llenos de preguntas,
como el carcelero del que se habla en Hechos,
que cayó temblando y les dijo a Pablo y a Silas: "`Señores,
¿qué debo hacer para ser salvo?`"
En compasión por sus pobres almas,
los exhorté fervientemente a soportar el juicio del Señor y Su
indignación (pues ellos habían pecado extremadamente contra Él),
para que pudieran encontrar misericordia de Él,
a través de la verdadera humillación y arrepentimiento;
además de otros consejos y advertencias necesarios,
según lo que me mostraba el Señor mediante Su luz,
que era lo más adecuado para la condición de ellos.

Yo no estaba familiarizado con este tipo de personas antes de las reuniones en Norwich.
La mayoría de ellos fueron convencidos de la verdad
y varios se reformaron en sus vidas y conducta;
aunque algunos volvieron a su corrupta libertad carnal,
por descuido y falta de vigilancia, pues no se mantuvieron en el temor de Dios.
De hecho, hemos visto en nuestro día, que dondequiera que la herida mortal en la bestia,^
footnote:[Apocalipsis 13:3]
o en la naturaleza bestial,
ha sido sanada en aquellos que no han avanzado a través de la muerte de la carne,
ni pacientemente esperado ver el juicio llevado a cabo en victoria, se han extraviado,
y han convertido la gracia de Dios en libertinaje a fin de abrazar el mundo.
Así, han vendido la verdad y a sí mismos, es decir, han vendido sus propias almas,
por sus iniquidades, tal como Isaías había testificado:
"`He aquí que por vuestras maldades sois vendidos.`"^
footnote:[Isaías 50:1]

[.asterism]
'''

+++[+++__Nota del editor:__
George Whitehead era uno de varios jóvenes mensajeros del evangelio sin educación,
que el Señor envió en ese tiempo de la parte norte
y rural de Inglaterra a la más poblada del sur,
a fin de llamar a una nación altiva al arrepentimiento,
y volverla de sus profesiones muertas y formales a la vida y luz de Jesucristo.
George Fox, James Parnell,
Richard Hubberthorn--que ya han sido mencionados--junto con Edward Burrough,
James Nayler, William Dewsbury, John Burnyeat y muchos otros,
aunque jóvenes en cuanto a edad y de apariencia poco impresionante,
descendieron a Londres, Bristol, Oxford, Reading y otras grandes ciudades,
revestidos de esa humildad,
sabiduría y autoridad que solo se obtienen en la escuela del Espíritu de Cristo.
Isaac Penington vivía entonces en Londres y era un diligente buscador del reino de Dios,
aunque aún no estaba en comunión con la Sociedad de Amigos.
Puede que al lector le interese la descripción que hace Isaac Penington
de estos "`jóvenes campesinos,`" cuando llegaron por primera vez del norte
con las buenas noticias de un cristianismo espiritual y sustancial.

"`+++[+++Considere ahora],
la insignificancia de las vasijas que el Señor escogió llenar de Su tesoro,
y por medio de las cuales comenzó a derramar esta dispensación de vida.
Ellos eran en su mayor parte humildes en cuanto a lo externo,
jóvenes campesinos carentes de entendimiento profundo o expresión fácil.
Dondequiera que fueran,
su apariencia era fácilmente despreciada por la sabiduría del hombre,
y solo podía ser reconocida en el poder de esa vida en la que fueron enviados.
¡Cuán ridícula fue su manera de aparecer y era su manera de actuar ante
el ojo del hombre! ¡Cuán pobres y triviales eran las circunstancias,
hábitos,
gestos y cosas sobre las que parecía que ponían gran peso y hacían un
asunto de gran importancia! ¡Cuán poco familiarizados parecía que estaban
de los misterios y profundidades de la religión! No obstante,
su predicación principal era el arrepentimiento, sobre una luz interior,
sobre volverse a ella,
y la proclama de que el grande y terrible día del Señor estaba cerca; por lo cual,
confieso, mi corazón los despreciaba enormemente,
y no me extraña que cualquier hombre sabio o profesante del cristianismo lo haya hecho,
o siga haciéndolo.
Sí,
ellos mismos estaban muy conscientes de su propia debilidad e incompetencia
para la gran obra y servicio con que el Señor los había honrado,
y de su incapacidad de razonar con el hombre.
Por tanto, en el temor y vigilancia de sus espíritus,
se apegaban a su testimonio y a los movimientos del poder de Dios,
al no buscar responder o satisfacer la parte racional del hombre,
sino solo buscando alcanzar y levantar el don de esa Semilla en el hombre,
a lo que su testimonio estaba dirigido.`"

"`¡Oh, cómo bendecía Dios el derramamiento de Su vida,
que Él había encomendado en sus manos! ¡Cómo los prosperaba el Señor,
al reunir Sus ovejas esparcidas y errantes en Su redil de reposo!
¡Cómo refrescaban a las almas hambrientas y sedientas sus palabras,
que caían como rocío! ¡Cómo alcanzaban la vida en aquellos a quienes ministraban,
al levantar eso que yacía como muerto en la tumba,
para que diera un testimonio vivo a la voz viva de Dios en ellos!
¡Cómo golpeaban la sabiduría y los razonamientos del hombre,
haciendo que su altivez se inclinara y postrara ante
el débil e ingenuo bebé! ¡Lo que ojo no ha visto,
ni oído ha escuchado, ni corazón de hombre ha concebido,
es lo que el poder de vida ha forjado a través de ellos,
en los corazones y consciencias de aquellos que han anhelado y esperado al Señor!`"

"`¡Oh, las respiraciones y derretimientos del alma,
la consciencia de la presencia viva de Dios, la sujeción del corazón a Dios,
el despertar y la dádiva de fuerza a Su Testigo interior,
la caída y debilitamiento de los poderes de las tinieblas,
el claro resplandor de la luz de vida en el corazón,
y el dulce correr de sus arroyos puros en las almas avivadas,
ha sido con frecuencia experimentado y confirmado por la
poderosa aparición de Dios en el ministerio de ellos!`"

"`De hecho, cuando he considerado estas y otras cosas similares en mi corazón,
y los he observado de cerca en mi interacción con ellos,
a menudo he sido forzado a exclamar con respecto a ellos: "`En verdad,
aquí hay un hombre muy débil y despreciable, pero un Dios muy glorioso y poderoso.`"
En realidad, cuando en algún momento miraba al hombre, apenas podía evitar despreciarlos,
pero, por otro lado,
cuando el ojo de mi espíritu contemplaba el poder y la gloria del Señor en ellos,
apenas podía evitar sobreestimarlos y exaltarlos.`"

"`¡Y ahora, muchos años después,
cómo ha llevado el Señor a estas vasijas a una mayor gloria,
desde que comenzó a usarlas! ¡Cómo las ha enriquecido Él con dones y habilidades,
y preparado en todos los sentidos para el servicio y empleo
que tenía para ellas! ¡Cómo ha extendido sus ministerios,
que aquellas que una vez tenían poco que decir,
ya fuera a manera de declaración o de disputa al principio, ahora abunda en fuerza,
y sobrepasan copiosamente el conocimiento y la sabiduría del mundo y de
otros profesantes de religión! ¡Ciertamente el Señor las ha adornado,
al poner Su belleza sobre ellas,
y hacerlas crecer en Su fuerza y en Su sabiduría!
Esto lo ha visto mi ojo y a menudo lo he notado,
al bendecir el nombre del Señor y orar a Él por la preservación de ellos.
De seguro, quienquiera que los haya conocido por sí mismo,
o haya oído el relato de la pobreza de estos jóvenes muchachos
cuando aparecieron por primera vez en el poder del Señor,
cuán vacíos estaban entonces,
cuán cuidadosos anduvieron arriba y abajo en su propia debilidad,
cuán poco tenían que decirle al pueblo que llegaba a observarlos y a inquirir de ellos,
cuán temerosos estaban de ser arrastrados de su vigilancia,
cuán lejos estaban de entrar en razonamientos de cosas; digo,
aquel que conoce y considera esto, y además,
contempla cómo el Señor los ha mejorado desde entonces,
haciéndolos poderosos y honorables con Sus dones y habilidades,
no puede sino admitir que el cambio es maravilloso.`"]

[.asterism]
'''

Por esta época conocí a nuestro anciano y fiel amigo, William Barber, de Gissing,
en el condado de Norfolk.
Yo les declaré la verdad a él y a algunos otros que estaban presentes,
y les aclaré algo del misterio de Cristo y del ministerio
y obra de Su Espíritu en el interior,
junto con la obra de oposición que hace el enemigo en el hombre,
según le plació al Señor revelar y capacitarme.
William fue muy tiernamente afectado, rompió en lágrimas y su espíritu se humilló,
aunque él había sido un hombre importante en el mundo y capitán del ejército.
La Verdad estaba cerca de él y yo lo sentía a él cerca de ella,
y mi corazón estaba abierto y tierno hacia él en el amor de Cristo.

Un tiempo después conocí a su esposa.
Ella era un mujer honesta y sobria,
que recibió la verdad y a los Amigos con gran amor y ternura,
y continuó siendo una Amiga fiel, inocente y amorosa hasta el día de su muerte.
Observé cómo la había dotado el Señor con mucha paciencia,
especialmente durante el grande y largo sufrimiento que experimentó
su esposo durante su encarcelamiento en el Castillo de Norwich,
por espacio de veinte años o más, principalmente,
por no pagar los diezmos al anciano sacerdote de la parroquia,
quien parecía implacablemente malicioso en su acusación, o más bien,
en su persecución y venganza.
William Barber dio fiel testimonio con paciencia y longanimidad.
No conozco a nadie que haya sufrido como él en esos lugares,
aunque muchos Amigos de los alrededores han sufrido profundamente por el mismo motivo,
y el Señor los ha sostenido.

Unos pocos días después, estando cerca el fin del décimo mes de 1654,
se iba a realizar una conferencia en Norwich, en la llamada iglesia de Pedro,
y sentí que se me pedía que asistiera y llevara testimonio
según el Señor se complaciera darme,
estando dotado de un celo santo contra la iniquidad,
el orgullo y la codicia de los altivos sacerdotes de aquellos días, así como también,
de compasión por la ignorancia y ceguera del pueblo engañado por ellos.

Cuando el sacerdote, un tal Boatman, terminó su sermón,
se me permitió decir muy poco--solo unas pocas palabras contra la iniquidad--antes de
que algunos de los oyentes del sacerdote cayeran violentamente sobre mí para sacarme,
algunos tirándome de un brazo y otros tirándome del otro brazo;
algunos tratando de sacarme por la puerta norte y otros por el pórtico sur.
Debido a la violencia de ellos sufrí algunas heridas y me dolía un costado de mi pecho,
pues fui fuertemente doblado cuando me tiraban y arrastraban en direcciones opuestas.
Pero le plació al Señor en pocos días,
sanarme las heridas y quitarme el dolor que había recibido por el maltrato.
De la '`casa del campanario`' fui arrastrado a Guild-hall, ante Thomas Toft, el alcalde,
quien después de examinarme acerca del bautismo en agua y de otras cosas,
me recluyó en la cárcel de la ciudad.

En poco más de dos meses, el primer mes de 1655,
fui liberado de mi cautiverio y viajé en Norfolk y Suffolk hacia Ingworth,
Lammas y esas partes, así como también Windham, Wramplingham y New Bucknam.
Mi querido amigo y hermano Richard Clayton estuvo conmigo en algunas reuniones en Norfolk,
donde había personas de mente dispuesta inquiriendo en pos del Señor y de Su verdad viva,
cuyos corazones Él había preparado para recibir el amor de la verdad.
Recuerdo bien de qué manera abrió el Señor mi corazón,
y me extendió en mi testimonio del evangelio hacia esas personas;
mucho fue en testimonio del amor y gracia universal de Dios,
la luz de Cristo dada a cada hombre.
Trabajé para volver sus mentes a ella,
y les mostré que ellos debían esperar en esa luz para conocer las enseñanzas de Dios,
y entrar en la dispensación del nuevo pacto,
en el que todo el pueblo de Dios es enseñado por Él y puede conocerlo,
desde el menor hasta el mayor,
al experimentar Su ley escrita en sus corazones y Su Espíritu en lo íntimo,
de acuerdo a Sus benditas promesas; porque este es el nuevo pacto eterno,
profetizado por los santos profetas evangélicos.

En este nuevo pacto,
no solo la casa de Israel y Judá pueden tener parte y ser partícipes de Cristo,
sino también todo verdadero creyente gentil,
para quienes Cristo ha sido dado como una luz y un pacto,
y como la salvación de Dios hasta los confines de la tierra.
Porque Dios no solo es el Dios de los judíos, sino también el Dios de los gentiles;
y los verdaderos judíos y el verdadero Israel, son aquellos que lo son espiritualmente,
es decir,
los que por medio de la circuncisión del corazón realizada por el Santo Espíritu de Dios,
son judíos internos.

A fin de someterse a esta dispensación y ministerio del nuevo pacto,
y allí conocer y experimentar a Cristo como su ministro, su maestro,
su sumo sacerdote y profeta, los animé a que dejaran al hombre,
y a todos los ministros y sacerdotes que habían sido hechos por la voluntad del hombre;
también a alejarse de los ministros asalariados que
predicaban por lucro inmundo y ganancia deshonesta,
que habían hecho un negocio de las sagradas Escrituras,
y les habían añadido sus propias imaginaciones, significados y conceptos,
al no tener revelación divina, ni haber recibido una comisión para predicar; mucho menos,
para hacer un negocio de las palabras y testimonios de los santos profetas,
de Cristo Jesús o de Sus apóstoles,
incluso mientras caminan en contra de los pasos y prácticas de ellos en orgullo y codicia.

El Señor a menudo me presionaba para que testificara
contra el orgullo y la codicia de los sacerdotes,
contra su predicación a cambio de un salario,
diezmos obligatorios y mantenimiento forzado,
contrario a los mandamientos de Cristo y al ejemplo de Sus ministros.
Por esta causa los líderes religiosos estaban llenos de envidia contra nosotros,
y en sus púlpitos exclamaban y hacían mucho ruido para encolerizar
al pueblo y a los magistrados contra los llamados Cuáqueros,
llegando incluso a severas persecuciones y encarcelamientos.
Sin embargo, sigue siendo un asunto memorable para mí,
que por la predicación viva de la luz, del nuevo pacto,
de la Palabra cerca de las personas en sus corazones, sí,
del evangelio de la gracia y del amor de Dios en Cristo hacia la humanidad,
muchos fueran real y efectivamente convencidos y
persuadidos de la bendita y eterna verdad,
como está en Cristo Jesús, en los condados de Norfolk, Suffolk y Essex,
donde el Señor me guió a viajar primero, y me ayudó y prosperó en Su servicio.
¡Bendito y alabado sea Su nombre para siempre!

Cerca de la primavera del mismo año de 1655,
John Lawrence fue convocado a una reunión en la iglesia parroquial en Norwich,
donde los líderes tenían la intención de excomulgarlo.
Yo fui con él y encontramos una gran concurrencia de hombres y mujeres,
junto con su pastor y ancianos.
Ellos repitieron sus acusaciones contra él, a saber, que él había abandonado su comunión,
hospedado a extraños o personas peligrosas, y sostenía doctrinas peligrosas.
Entonces John Lawrence dio las razones que lo llevaron a dejar su comunión,
respondiendo que el apóstol Pablo había exhortado a todos
a volverse de los hombres que "`tendrán apariencia de piedad,
pero negarán el poder de ella,`" quienes eran "`amadores de sí mismos, avaros,
vanagloriosos, soberbios,`"^
footnote:[2 Timoteo 3:2-5 (RV1602 Purificada)] etc.

Después de esto, en el temor y pavor del Señor,
me puse de pie para decir unas pocas palabras entre ellos,
pero rápidamente me derribaron y me sostuvieron por la fuerza en el banco en que estábamos.
Algunos de sus miembros me arrastraron enérgicamente y me empujaron hacia
fuera de la '`casa del campanario,`' y me expusieron a una turba violenta,
que estaba lista para poner sus manos sobre mí. Ellos me empujaron
y me arrastraron por las calles y el mercado de la ciudad,
y algunas veces me tiraron sobre las piedras, por lo que estaba lesionado y herido.
Me siguieron, me rodearon, y me empujaron rugiendo y gritando,
hasta que llegué cerca de la puerta de la ciudad llamada
'`puerta de Giles,`' a un lado de un pequeño pastizal.
En la parte alta del pastizal vi una gran casa,
donde habitaba la señora Hubbard (según entendí después). Cuando vi la casa,
me encontré en un gran dilema en mi mente--teniendo
la turba a mi alrededor--si debía salir de la ciudad,
a fin de ir a la casa de John Lawrence en Wramplingham, lo cual deseaba,
o si debía volverme hacia esa gran casa,
deseando que el Señor me dirigiera en ese instante.

Pensé que si salía de la ciudad por el camino hacia Wramplingham,
estaría en peligro de perder mi vida en el camino, o en un campo,
por causa de la violenta y tumultuosa compañía que me rodeaba,
y mi muerte sería menos notada.
Pero si iba a perder mi vida,
pensé que sería mejor perderla donde pudiera dar
mi testimonio dentro de la ciudad de Norwich,
y donde había comenzado la persecución,
en lugar de ser asesinado en secreto por una turba fuera de la ciudad o en un campo;
pues estaba rendido a sufrir cualquier violencia que el Señor les permitiera hacerme.

Tras reflexionarlo, me volví inmediatamente hacia la casa de la señora Hubbard,
escoltado por la furiosa compañía que continuaba a mi alrededor.
Por causa del ruido y de los gritos, el capellán de la señora, Dr. Collins,
y la mayoría de la familia, rápidamente salieron a ver qué sucedía,
y por qué tanta gente se había acercado a la casa de ellos.
Cuando vieron que yo era la persona asediada y perseguida,
el capellán (entendiendo que yo era un Cuáquero) comenzó a hablar
conmigo con respecto al Espíritu que tenían los apóstoles de Cristo,
y me preguntó si yo tenía el mismo Espíritu.
Yo admití que participaba del mismo Espíritu en mi medida, y que sin embargo,
no igualaría mi grado de alcance al de ellos.
El capellán replicó que si yo tenía ese Espíritu, por qué no lo probaba con una señal,
un milagro, o hablando en lenguas, como habían hecho los apóstoles.
Yo le respondí con las palabras de Pablo sobre este tema,
hablándole de la diversidad de dones dados por el único y mismo Espíritu.
Le dije, que no todos los que tenían el Espíritu de Cristo tenían los mismo dones,
como hablar en lenguas y hacer milagros; '`porque a uno le es dado palabra de sabiduría,
a otro palabra de conocimiento, a otro fe, a otro hacer milagros, a otro profecía,
a otro diferentes tipos de lenguas, a otro interpretación de lenguas,
pero todo por el mismo Espíritu,`' el Espíritu y poder de Cristo.
Y que era evidente que esos dones de lenguas y milagros,
no eran algo común en todos los que tenían el Espíritu de Cristo en la primera iglesia,
sino algo particular en algunos, como lo indican estas preguntas de Pablo:
"`¿Son todos apóstoles?
¿son todos profetas?
¿todos maestros?
¿hacen todos milagros?
¿tienen todos dones de sanidad?
¿hablan todos lenguas?
¿interpretan todos?`"^
footnote:[1 Corintios 12:29-30]
Y de hecho,
que esto mostraba que no todos los ministros y miembros de la iglesia
estaban igualmente dotados en todos estos aspectos,
aunque todos tenían el único y mismo Espíritu de quien provenían estos dones.

Cuando el capellán se dio cuenta de cuán revoltoso y rudo había sido el grupo contra mí,
me preguntó por qué yo no los callaba o reprimía,
si realmente tenía el mismo Espíritu o poder que habían tenido los apóstoles.
Yo le respondí,
que el propio apóstol Pablo deseaba que la iglesia de Tesalónica orara por él,
para que el Señor lo librara de las manos de hombres irracionales,
porque no todos tenían fe.
Y que él, algunas veces había estado en manos de hombres irracionales y en disturbios,
pero que el Señor lo había librado de sus manos.

Mientras hablábamos, mis perseguidores estaban en silencio,
formando un círculo alrededor de nosotros,
y oyéndonos hablar de los temas antes relatados.
La conversación duró poco, supongo que una media hora.
Entretanto, un soldado u oficial subió con su espada a un costado,
y al darse cuenta que yo era la persona perseguida y hostigada por la turba,
se aceró y me dijo que él me acompañaría y me protegería hasta mi alojamiento.
Luego, poniendo su mano sobre su espada,
le ordenó a la multitud que se hiciera a un lado y abriera paso.
Así fui tranquilamente rescatado,
y él me acompañó a la casa de mi querido amigo Thomas Symonds, en la ciudad.

Vi que había sido el Señor quien había puesto en
mi mente acercarme a la casa de la señora Hubbard,
cuando estaba en peligro por la turba, y también,
quien había movido la mente de un extraño para que me rescatara de las manos
de hombres irracionales que me habían rodeado y maltratado con violencia.
Muchas veces he estado agradecido con Dios por Su misericordiosa providencia
en esa liberación. El soldado que tuvo tal cuidado para rescatarme,
después se convirtió en un Amigo, y entró en sociedad con el pueblo llamado Cuáqueros,
donde el Señor le mostró misericordia.
Su nombre era Robert Turner, de Lynn, en Norfolk.
Yo no supe que él era el hombre que me había rescatado, hasta veinticinco años después,
cuando yo estaba otra vez prisionero en el Castillo de Norwich, con muchos Amigos más,
en el año 1680.

En aquellos días las prisiones y cárceles se convirtieron
en santuarios y en lugares de refugio para nosotros,
de la furia de la revoltosa multitud,
aunque también nos topamos con malos y duros tratos
en esos lugares de confinamiento severo,
muchas veces entre criminales muy conocidos.
Pero aunque yo sufrí duro trato, tanto por los tumultos como por los encarcelamientos,
el Señor me ayudó y me sostuvo por medio de Su poder y bondad divinos,
de modo que no me cansé de Su servicio, ni mi espíritu se debilitó en el sufrimiento.
El agradecido recuerdo de Su bondad,
y el sentido vivo de Su amor por mi alma en aquellos días,
todavía viven y permanecen sobre mi espíritu.
¡Alabado sea nuestro Dios por los siglos de los siglos!
